### ISSUE TITLE
Errors: `command armadev.previewControl' not found

### ISSUE THREAD

**Issue by ghost** [ole1986/vscode-arma-dev#1]
I'am having errors: `command armadev.previewControl' not found` when i use option `Dialog preview` or just nothing happens after i press that. That happens after i am trying to preview dialog second or xx time, sometimes it happen on first try
All dirrectorys are set. VS Code version 1.19.1

**Comment by ole1986** [comment]
Hi and thank you for reporting.

I already noted this, when you directly call the command instead of using it from the explorers centext menu.

So, to workaround this you need to right-click the *.hpp to open the context menu and select the Preview here.

**Comment by ghost** [comment]
Ok thanks

**Comment by ZwinkaDink** [comment]
is this fixed yet

**Comment by irvnriir** [comment]
@ole1986 no such option in the context menu

**Comment by ole1986** [comment]
@Ilias48rus  initialized the extension properly by usiing Arma 3: configure?

**Comment by irvnriir** [comment]
@ole1986 filled the form, now it shows this:
![pizmiszsqfintxvisualstudiocode](https://user-images.githubusercontent.com/13949704/47909648-98d50b80-dea1-11e8-9fd6-8b8a1995891e.PNG)
; and no option in the context menu, and if you made the script to preview the gui, i have no idea why was needed to rely it on any other,unrelated parts of the package.

**Comment by ole1986** [comment]
you can create a new issue an attach your hpp file which may show incorrectly.

We will then work on it. 

Thank you

**Comment by irvnriir** [comment]
[configXadiZshoXarma3.txt](https://github.com/ole1986/vscode-arma-dev/files/2543825/configXadiZshoXarma3.txt)
