### ISSUE TITLE
Code live puts the junction in the wrong directory

### ISSUE THREAD

**Issue by BrightCandle** [ole1986/vscode-arma-dev#2]
I use multiple SteamLibraries and while Steam is installed on the D drive my Arma 3 installation is actually on the C drive. Unfortunately Code live currently makes an Arma 3 directory and places its junction in there, which doesn't actually work since Arma is not installed in that location.

Rather than trying to work it out on the basis of SteamLibraries and everything else it may be simpler to provide a config value that allows overriding the Arma 3 installation directory in the case where people (like myself) are doing something different than the norm.

**Comment by ole1986** [comment]
Thank you for reporting this issue.
I am going to update the extension allowing you to place the steam path manually.

**Comment by BrightCandle** [comment]
You legend that actually work wonders! Many many many thanks.

**Comment by ole1986** [comment]
dont forget to rate it on the vscode marketplace ;-)
