### ISSUE TITLE
A proper PREFIX (x\your_addonname) is required

### ISSUE THREAD

**Issue by Bortfive** [ole1986/vscode-arma-dev#4]
i am getting this A proper PREFIX (x\your_addonname) is required for life_server\addons\life_server(editado)
and i have a $PBOPREFIX$ in the folder life_server with "prefix=life_server"
i Try to put only life_server on $pboprefix$.

Thanks for all <3

**Comment by ole1986** [comment]
Begin the path name with an  "x\"
So the $PBOPREFIX$ should contain:

x\your_extension

**Comment by Bortfive** [comment]
OK, its working now, Thanks.

And now, why when i put Arma 3 : Run  server


[11:33:18.562][Info] Running Arma3Server: -autoInit  "-profiles=C:\Users\Bortfive\AppData\Local\Arma 3\ArmaDevServer" "-config=C:\Users\Bortfive\AppData\Local\Arma 3\ArmaDevServer\server.cfg" -serverMod=c:\Users\Bortfive\Documents\Github\ProyectoX\build\@LifeServer
[11:33:18.594][Error] Failed to run Arma3Server

I run the server without ur extension, Where i can edit to use the Togle Live code? In Github? https://i.imgur.com/PGzIDK0.png
Inside the workspace? I try to edit and recompile on arma 3 and didn't obtain any result

**Comment by ole1986** [comment]
it looks like the path for `serverMod=c:\Users\Bortfive\Documents\Github\ProyectoX\build@LifeServer` is missing a "\".

Can you try to change the "buildPath" from "build/" to "build" only and retry?

For "Code Live" please read the section [Toggle Code Live](https://github.com/ole1986/vscode-arma-dev/blob/master/README.md#toggle-code-live) carefully. Usually you can (re)run your scripts from the debug console in-game using execVM "x\youraddon\yourfile.sqf" (as long it is allowed through your mission file config)

IMPORTANT NOTE: Whenever you run "Code Live" your source  will be linked to your Arma3 game directory. So it becomes available as "x\your_game_addon" in the ARma3 folder. If you remove filed inside the "Arma3\x\your_game_addon", it will also be removed from your workspace folder. Delete with caution!

**Comment by Bortfive** [comment]
I change build/ to Build and don't work neither, but don't worry. Thanks, U can close this <3
