### ISSUE TITLE
Unable to use extension

### ISSUE THREAD

**Issue by hobnob11** [ole1986/vscode-arma-dev#5]
[03:37:11.951][Error] TypeError: Cannot read property 'postProcess' of undefined
Get the above error when trying to use arma 3: Configure

**Comment by ole1986** [comment]
How does your .vscode/arma-dev.json file look like?

Is there a "postProcess" property defined?

**Comment by hobnob11** [comment]
The file does not exist.

**Comment by ole1986** [comment]
Ah. so its first time use actually

**Comment by hobnob11** [comment]
yes

**Comment by ole1986** [comment]
I am sorry for the delay I always wanted to send you an "empty" configuration as workaround so you may not need to use the command `Arma 3: Configure`

So you can add the below configuration as "template" as`.vscode/arma-dev.json` file

```
{
	"title": "Your mod title",
	"name": "YourModName",
	"author": "authorName",
	"website": "https://github.com/optional/repo/location",
	"version": "1.0.0",
	"buildPath": "./",
	"privateKey": "yourprivkey.biprivatekey",
	"serverDirs": [
		"source\\yourmed_server"
	],
	"serverMods": [
		"@ExileServer"
	],
	"serverParams": "",
	"serverUse32bit": true,
	"clientDirs": [
		"source\\yourmod_client"
	],
	"clientMods": [
		"@Exile"
	]
}
```

An example project working with arma-dev.json configuration can be found here:
https://github.com/ole1986/a3-admintoolkit

For further details on the settings, checkout the schema file:
[schemas/arma-dev.schema.json](https://github.com/ole1986/vscode-arma-dev/blob/master/schemas/arma-dev.schema.json)
