### ISSUE TITLE
Getting started workflow guidance

### ISSUE THREAD

**Issue by mwpowellhtx** [ole1986/vscode-arma-dev#8]
I might have misfiled this one. I found this [in a search](/ole1986/a3-admintoolkit/issues/50) involving `VSCode`. Looking more for modding VS Code extensions, tooling, than anything else.

Mainly I am interested in practical examples of this, if possible. That would be helpful.

This helps to streamline modding workflow? Can it be used in combination with extensions such as `armake2`, etc?

Anyway, still have some questions I am not as clear concerning:

```JSON
"clientDirs": {
    "description": "A list of all client folders (usually one) a pbo file should be generated and signed for"
},
```

```JSON
"serverDirs": {
    "description": "A list of all server folders a pbo file should be generated for"
},
```

Not sure how client/server directories quite applies? Is there a particular protocol that A3 will use? I see, for instance, `addons`, sometimes.

```JSON
"clientMods": {
    "type":"array",
    "description": "Additional mods to include when starting the arma3 client"
},
```

As in mod `dependencies`? How are they named? By whatever workshop ID was used, i.e. `@MyMod`?

```JSON
"postProcess": {
    "type": "object",
    "description": "Used to run additional scripts, once a commend has been executed",
    "properties": {
        "packFolders": {
            "type": "string",
            "description": "Define a script to run after all folders have been packed"
        },
        "transferFiles": {
            "type": "string",
            "description": "Define a script to run after all files are transfered to the remote"
        },
        "runClient": {
            "type": "string",
            "description": "Define a script to run after arma is started"
        },
        "runClientAndLog": {
            "type": "string",
            "description": "Define a script to run after arma is started (with logfile opened)"
        },
        "generateKey": {
            "type": "string",
            "description": "Define a script to run after a bikey has been generated"
        }
    }
}
```

Post processing sounds interesting. Q: to which remote? Does a `bikey` always get generated? Or just running batch, PowerShell, [or other scripts in a command shell](/ole1986/vscode-arma-dev#post-processing)?

Still not clear on the use of `SFTP` vis-à-vis A3 modding. I assume this is to publish to workshop, or any other resource?

Thanks!

**Comment by ole1986** [comment]
Arma 3 AdminToolkit is one of my examples using Arma Dev

https://github.com/ole1986/a3-admintoolkit
Its configuration file is located here: https://github.com/ole1986/a3-admintoolkit/blob/master/.vscode/arma-dev.json
